---
- name: Install and Configure Cockpit
  hosts: your_servers
  become: true

  tasks:
    - name: Update apt cache (for Ubuntu)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install Cockpit package
      ansible.builtin.package:
        name: cockpit
        state: present
      become: true

    - name: Start Cockpit service and enable it on boot
      ansible.builtin.service:
        name: cockpit
        state: started
        enabled: true
